<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('global');
        $this->load->helper('system');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $isLoggedIn = $this->session->userdata('logged_in');
      
	    if(!isset($isLoggedIn) || $isLoggedIn != TRUE){
	          redirect('/LoginControllers');
	    }else{
	    	$userId = $this->session->userdata('user_id');

        	$data['prescription'] = $this->db->order_by('prescription_id','DESC')->get_where('prescription',array('customer_id' => $userId))->result();

	        $this->load->view('header');
	        $this->load->view('sidebarcustomer');
	        $this->load->view('dashboard/dashboard', $data);
	        $this->load->view('footer'); 
        }  
    }

    public function read($id){
      $isLoggedIn = $this->session->userdata('logged_in');
      
      if(!isset($isLoggedIn) || $isLoggedIn != TRUE)
      {
          redirect('/LoginControllers');
      }
      else
      {
        $query = $this->db->get_where('prescription', array('prescription_id' => $id));
        $data['prescription'] = $query->row();

        $data['CC'] = $this->db->get_where('problem',array('prescription_id' => $id))->result();
        $data['advice'] = $this->db->get_where('getadvice',array('prescription_id' => $id))->result();
        $data['prescriptiondata'] = $this->db->get_where('prescription_item',array('prescription_id' => $id))->result();

        
        $this->load->view('dashboard/previewdata',$data);
      }
    }

    public function serial(){
    	$isLoggedIn = $this->session->userdata('logged_in');      
	    if(!isset($isLoggedIn) || $isLoggedIn != TRUE){
	        redirect('/LoginControllers');
	    }else{
	    	$userId = $this->session->userdata('user_id');

	    	$data['serial'] = $this->db->order_by('serial_no','DESC')->get_where('serial',array('customer_id' => $userId))->result();

	    	$this->load->view('header');
	        $this->load->view('sidebarcustomer');
	        $this->load->view('dashboard/serial', $data);
	        $this->load->view('footer');

	    }
    }

    public function booking(){
    	$userId = $this->session->userdata('user_id');
    	$date = $this->input->post('date',TRUE);


    	$query = $this->db->get_where('serial', array('date' => $date));

    	$numrow = $query->num_rows();

    	

    	if ($numrow  <  30 ) {

    		$data = array( 
	    		'customer_id' => $userId, 
	    		'date' => $date, 
	    	);

	    	$this->db->insert('serial',$data);

	    	$this->session->set_flashdata('message', '<div style="margin-top: 12px" class="alert alert-success" id="message">Create Record Success</div>');
	    	redirect('dashboard/serial');

    	}else{
    		$this->session->set_flashdata('message', '<div style="margin-top: 12px" class="alert alert-dangar" id="message">Appointment date not available on this date</div>');
	    	redirect('dashboard/serial');
    	}

    	




    	// print $date;
    	// print "</br>";
    	// print date('Y-m-d');
    }

    

}

/* End of file Category.php */
/* Location: ./application/controllers/Category.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-13 14:33:18 */
/* http://harviacode.com */