<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Serial extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->helper('global');
        $this->load->helper('system');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $isLoggedIn = $this->session->userdata('logged_in');
      
        if(!isset($isLoggedIn) || $isLoggedIn != TRUE){
            redirect('/LoginControllers');
        }else{
        
            
            $data['serial'] = $this->db->limit(30)->get_where('serial', array('date' => date('Y-m-d')))->result();

            $this->load->view('header');
            $this->load->view('sidebar');
            $this->load->view('serial/serial_list', $data);
            $this->load->view('footer'); 
        }  


    }

    

    public function _rules() 
    {
    	$this->form_validation->set_rules('name', 'name', 'trim|required');
    	$this->form_validation->set_rules('phone', 'phone', 'trim|required');
    	$this->form_validation->set_rules('age', 'age', 'trim|required');
        $this->form_validation->set_rules('password', 'password', 'trim|required');
        $this->form_validation->set_rules('con_password', 'Confirm Password', 'required|matches[password]');

    	$this->form_validation->set_rules('customer_id', 'customer_id', 'trim');
    	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    

}

/* End of file customer.php */
/* Location: ./application/controllers/customer.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-13 14:33:18 */
/* http://harviacode.com */